import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/customs/header";

export const metadata: Metadata = {
  title: "Do it!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`min-h-screen bg-background text-foreground  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
